### PR TITLE
Added (mostly on archival basis) the Dockerfile which uses a locally …

### PR DESCRIPTION
**Pull request by buddhasystem**
I added a "legacy" version of the Dockerfile which uses a cached copy of .astropy. It's not the main "official" version of the Dockerfile but convenient to have if one is rebuilding images locally and frequently. We can improve this later.

### CODE REVIEW

**Comment by buddhasystem** [comment]
A trivial small addition. I decided to take advantage of the branch before it's gone.

**Review by slosar — APPROVED** [review]
Looks good.

**Comment by buddhasystem** [comment]
Thanks. Will merge (this doesn't really require CI).

**Comment by buddhasystem** [comment]
Should I delete the "fix" branch?

**Comment by slosar** [comment]
Yes, branches should be always deleted immediately after merging so we don't proliferate branches.
In general we never merge a branch into main more then once, but it is ok to merge main into branch as often as needed to keep it up to date.

**Pull request merged**
