### PR TITLE
add pyproject.toml lines to make this a package

### PR DESCRIPTION
**Pull request by xzackli**
This PR adds some lines to pyproject.toml so that one can install this as a package with 
```
flit install
```
for i.e. local development.

### CODE REVIEW

**Comment by buddhasystem** [comment]
I defer it to Anze since that's an important step. It sounds great, of course.

**Review by slosar — APPROVED** [review]
I have nothing to complain here!

**Comment by slosar** [comment]
I don't understand why it doesn't run the github actions workflow. Even when  I run it manually it just contines to say "Some checks haven't completed yet." Will override for now, but this needs fixing.

**Comment by slosar** [comment]
It used to work last time.

**Pull request merged**
